export const sampleJourneys = {
  minStart: '2022-04-11T23:21:00.000Z',
  maxEnd: '2022-04-12T01:07:00.000Z',
  trips: [
    {
      idx: 2,
      uid: 'arnu|fromLocation=52.445937,4.81496|toLocation=52.367926,4.882755|plannedFromTime=2022-04-11T23:21:00+02:00|originWalk=true|destinationWalk=true|plannedArrivalTime=2022-04-12T00:09:00+02:00|yearCard=false|excludeHighSpeedTrains=false|searchForAccessibleTrip=false',
      ctxRecon:
        'arnu|fromLocation=52.445937,4.81496|toLocation=52.367926,4.882755|plannedFromTime=2022-04-11T23:21:00+02:00|originWalk=true|destinationWalk=true|plannedArrivalTime=2022-04-12T00:09:00+02:00|yearCard=false|excludeHighSpeedTrains=false|searchForAccessibleTrip=false',
      plannedDurationInMinutes: 48,
      actualDurationInMinutes: 48,
      transfers: 0,
      status: 'NORMAL',
      messages: [],
      legs: [
        {
          idx: '0',
          travelType: 'WALK',
          cancelled: false,
          changePossible: true,
          alternativeTransport: false,
          origin: {
            name: '',
            lng: 4.81496,
            lat: 52.445937,
            type: 'ADDRESS',
            plannedTimeZoneOffset: 120,
            plannedDateTime: '2022-04-11T23:21:00+0200',
            checkinStatus: 'NOTHING',
            notes: [],
          },
          destination: {
            name: 'Zaandam',
            lng: 4.81361103057861,
            lat: 52.4388885498047,
            countryCode: 'NL',
            uicCode: '8400731',
            type: 'STATION',
            plannedTimeZoneOffset: 120,
            plannedDateTime: '2022-04-11T23:34:00+0200',
            checkinStatus: 'NOTHING',
            notes: [],
          },
          product: {
            type: 'WALK',
          },
          messages: [],
          stops: [
            {
              name: '',
              lat: 52.445937,
              lng: 4.81496,
              notes: [],
              routeIdx: 0,
              plannedDepartureDateTime: '2022-04-11T23:21:00+0200',
              plannedDepartureTimeZoneOffset: 120,
              cancelled: false,
              borderStop: false,
              passing: false,
            },
            {
              uicCode: '8400731',
              name: 'Zaandam',
              lat: 52.4388885498047,
              lng: 4.81361103057861,
              countryCode: 'NL',
              notes: [],
              routeIdx: 1,
              plannedArrivalDateTime: '2022-04-11T23:34:00+0200',
              plannedArrivalTimeZoneOffset: 120,
              cancelled: false,
              borderStop: false,
              passing: false,
            },
          ],
          shorterStock: false,
          reachable: true,
          plannedDurationInMinutes: 13,
        },
        {
          idx: '1',
          name: 'SPR 4091',
          travelType: 'PUBLIC_TRANSIT',
          direction: 'Rotterdam Centraal',
          cancelled: false,
          changePossible: true,
          alternativeTransport: false,
          journeyDetailRef:
            'HARP_S2S-2|#VN#1#ST#1649241339#PI#0#ZI#441324#TA#0#DA#110422#1S#1101147#1T#2318#LS#1100688#LT#10104#PU#784#RT#1#CA#SPR#ZE#4091#ZB#SPR 4091#PC#3#FR#1101147#FT#2318#TO#1100688#TT#10104#',
          origin: {
            name: 'Zaandam',
            lng: 4.81361103057861,
            lat: 52.4388885498047,
            countryCode: 'NL',
            uicCode: '8400731',
            type: 'STATION',
            plannedTimeZoneOffset: 120,
            plannedDateTime: '2022-04-11T23:35:00+0200',
            plannedTrack: '5',
            actualTrack: '5',
            checkinStatus: 'CHECKIN',
            notes: [],
          },
          destination: {
            name: 'Amsterdam Centraal',
            lng: 4.90027761459351,
            lat: 52.3788871765137,
            countryCode: 'NL',
            uicCode: '8400058',
            type: 'STATION',
            plannedTimeZoneOffset: 120,
            plannedDateTime: '2022-04-11T23:47:00+0200',
            plannedTrack: '5',
            actualTrack: '5b',
            exitSide: 'RIGHT',
            checkinStatus: 'CHECKOUT',
            notes: [],
          },
          product: {
            number: '4091',
            categoryCode: 'SPR',
            shortCategoryName: 'SPR',
            longCategoryName: 'Sprinter',
            operatorCode: 'ns',
            operatorName: 'NS',
            operatorAdministrativeCode: 100,
            type: 'TRAIN',
            displayName: 'NS Sprinter',
          },
          messages: [],
          stops: [
            {
              uicCode: '8400731',
              name: 'Zaandam',
              lat: 52.4388885498047,
              lng: 4.81361103057861,
              countryCode: 'NL',
              notes: [],
              routeIdx: 0,
              plannedDepartureDateTime: '2022-04-11T23:35:00+0200',
              plannedDepartureTimeZoneOffset: 120,
              actualDepartureTrack: '5',
              plannedDepartureTrack: '5',
              plannedArrivalTrack: '5',
              actualArrivalTrack: '5',
              cancelled: false,
              borderStop: false,
              passing: false,
            },
            {
              uicCode: '8400059',
              name: 'Amsterdam Sloterdijk',
              lat: 52.3888893127441,
              lng: 4.83777761459351,
              countryCode: 'NL',
              notes: [],
              routeIdx: 1,
              plannedDepartureDateTime: '2022-04-11T23:41:00+0200',
              plannedDepartureTimeZoneOffset: 120,
              plannedArrivalDateTime: '2022-04-11T23:41:00+0200',
              plannedArrivalTimeZoneOffset: 120,
              actualDepartureTrack: '6',
              plannedDepartureTrack: '6',
              plannedArrivalTrack: '6',
              actualArrivalTrack: '6',
              cancelled: false,
              borderStop: false,
              passing: false,
            },
            {
              uicCode: '8400058',
              name: 'Amsterdam Centraal',
              lat: 52.3788871765137,
              lng: 4.90027761459351,
              countryCode: 'NL',
              notes: [],
              routeIdx: 2,
              plannedArrivalDateTime: '2022-04-11T23:47:00+0200',
              plannedArrivalTimeZoneOffset: 120,
              actualDepartureTrack: '5b',
              plannedDepartureTrack: '5',
              plannedArrivalTrack: '5',
              actualArrivalTrack: '5b',
              cancelled: false,
              borderStop: false,
              passing: false,
            },
          ],
          crowdForecast: 'LOW',
          punctuality: 100,
          shorterStock: false,
          journeyDetail: [
            {
              type: 'TRAIN_XML',
              link: {
                uri: '/api/v2/journey?id=HARP_S2S-2|#VN#1#ST#1649241339#PI#0#ZI#441324#TA#0#DA#110422#1S#1101147#1T#2318#LS#1100688#LT#10104#PU#784#RT#1#CA#SPR#ZE#4091#ZB#SPR 4091#PC#3#FR#1101147#FT#2318#TO#1100688#TT#10104#&train=4091&datetime=2022-04-11T23:35:00+02:00',
              },
            },
          ],
          reachable: true,
          plannedDurationInMinutes: 12,
        },
        {
          idx: '2',
          travelType: 'WALK',
          cancelled: false,
          changePossible: true,
          alternativeTransport: false,
          origin: {
            name: 'Amsterdam Centraal',
            lng: 4.90027761459351,
            lat: 52.3788871765137,
            countryCode: 'NL',
            uicCode: '8400058',
            type: 'STATION',
            plannedTimeZoneOffset: 120,
            plannedDateTime: '2022-04-11T23:48:00+0200',
            checkinStatus: 'NOTHING',
            notes: [],
          },
          destination: {
            name: '',
            lng: 4.882755,
            lat: 52.367926,
            type: 'ADDRESS',
            plannedTimeZoneOffset: 120,
            plannedDateTime: '2022-04-12T00:09:00+0200',
            checkinStatus: 'NOTHING',
            notes: [],
          },
          product: {
            type: 'WALK',
          },
          messages: [],
          stops: [
            {
              uicCode: '8400058',
              name: 'Amsterdam Centraal',
              lat: 52.3788871765137,
              lng: 4.90027761459351,
              countryCode: 'NL',
              notes: [],
              routeIdx: 0,
              plannedDepartureDateTime: '2022-04-11T23:48:00+0200',
              plannedDepartureTimeZoneOffset: 120,
              cancelled: false,
              borderStop: false,
              passing: false,
            },
            {
              name: '',
              lat: 52.367926,
              lng: 4.882755,
              notes: [],
              routeIdx: 1,
              plannedArrivalDateTime: '2022-04-12T00:09:00+0200',
              plannedArrivalTimeZoneOffset: 120,
              cancelled: false,
              borderStop: false,
              passing: false,
            },
          ],
          shorterStock: false,
          reachable: true,
          plannedDurationInMinutes: 21,
        },
      ],
      crowdForecast: 'LOW',
      punctuality: 100,
      optimal: true,
      fareRoute: {
        routeId: '=KRkakyWBdA==',
        origin: {
          varCode: 731,
          name: 'Zaandam',
        },
        destination: {
          varCode: 58,
          name: 'Amsterdam Centraal',
        },
      },
      fares: [
        {
          priceInCents: 484,
          product: 'OVCHIPKAART_ENKELE_REIS',
          travelClass: 'FIRST_CLASS',
          discountType: 'NO_DISCOUNT',
        },
        {
          priceInCents: 290,
          product: 'OVCHIPKAART_ENKELE_REIS',
          travelClass: 'SECOND_CLASS',
          discountType: 'NO_DISCOUNT',
        },
        {
          priceInCents: 387,
          product: 'OVCHIPKAART_ENKELE_REIS',
          travelClass: 'FIRST_CLASS',
          discountType: 'DISCOUNT_20_PERCENT',
        },
        {
          priceInCents: 232,
          product: 'OVCHIPKAART_ENKELE_REIS',
          travelClass: 'SECOND_CLASS',
          discountType: 'DISCOUNT_20_PERCENT',
        },
        {
          priceInCents: 290,
          product: 'OVCHIPKAART_ENKELE_REIS',
          travelClass: 'FIRST_CLASS',
          discountType: 'DISCOUNT_40_PERCENT',
        },
        {
          priceInCents: 174,
          product: 'OVCHIPKAART_ENKELE_REIS',
          travelClass: 'SECOND_CLASS',
          discountType: 'DISCOUNT_40_PERCENT',
        },
        {
          priceInCents: 968,
          product: 'OVCHIPKAART_RETOUR',
          travelClass: 'FIRST_CLASS',
          discountType: 'NO_DISCOUNT',
        },
        {
          priceInCents: 580,
          product: 'OVCHIPKAART_RETOUR',
          travelClass: 'SECOND_CLASS',
          discountType: 'NO_DISCOUNT',
        },
        {
          priceInCents: 774,
          product: 'OVCHIPKAART_RETOUR',
          travelClass: 'FIRST_CLASS',
          discountType: 'DISCOUNT_20_PERCENT',
        },
        {
          priceInCents: 464,
          product: 'OVCHIPKAART_RETOUR',
          travelClass: 'SECOND_CLASS',
          discountType: 'DISCOUNT_20_PERCENT',
        },
        {
          priceInCents: 580,
          product: 'OVCHIPKAART_RETOUR',
          travelClass: 'FIRST_CLASS',
          discountType: 'DISCOUNT_40_PERCENT',
        },
        {
          priceInCents: 348,
          product: 'OVCHIPKAART_RETOUR',
          travelClass: 'SECOND_CLASS',
          discountType: 'DISCOUNT_40_PERCENT',
        },
        {
          priceInCents: 14970,
          product: 'TRAJECT_VRIJ_MAAND',
          travelClass: 'FIRST_CLASS',
          discountType: 'NO_DISCOUNT',
        },
        {
          priceInCents: 8860,
          product: 'TRAJECT_VRIJ_MAAND',
          travelClass: 'SECOND_CLASS',
          discountType: 'NO_DISCOUNT',
        },
        {
          priceInCents: 12240,
          product: 'TRAJECT_VRIJ_JAAR',
          travelClass: 'FIRST_CLASS',
          discountType: 'NO_DISCOUNT',
        },
        {
          priceInCents: 7240,
          product: 'TRAJECT_VRIJ_JAAR',
          travelClass: 'SECOND_CLASS',
          discountType: 'NO_DISCOUNT',
        },
        {
          priceInCents: 146888,
          product: 'BUSINESS_CARD_TRAJECT_VRIJ_JAAR',
          travelClass: 'FIRST_CLASS',
          discountType: 'NO_DISCOUNT',
        },
        {
          priceInCents: 86851,
          product: 'BUSINESS_CARD_TRAJECT_VRIJ_JAAR',
          travelClass: 'SECOND_CLASS',
          discountType: 'NO_DISCOUNT',
        },
      ],
      fareLegs: [
        {
          origin: {
            name: 'Zaandam',
            lng: 4.81361103057861,
            lat: 52.4388885498047,
            countryCode: 'NL',
            uicCode: '8400731',
            type: 'STATION',
          },
          destination: {
            name: 'Amsterdam Centraal',
            lng: 4.90027761459351,
            lat: 52.3788871765137,
            countryCode: 'NL',
            uicCode: '8400058',
            type: 'STATION',
          },
          operator: 'NS',
          productTypes: ['TRAIN'],
          fares: [
            {
              priceInCents: 290,
              priceInCentsExcludingSupplement: 290,
              supplementInCents: 0,
              buyableTicketSupplementPriceInCents: 0,
              product: 'OVCHIPKAART_ENKELE_REIS',
              travelClass: 'SECOND_CLASS',
              discountType: 'NO_DISCOUNT',
            },
          ],
        },
      ],
      productFare: {
        priceInCents: 290,
        priceInCentsExcludingSupplement: 290,
        buyableTicketPriceInCents: 290,
        buyableTicketPriceInCentsExcludingSupplement: 290,
        product: 'OVCHIPKAART_ENKELE_REIS',
        travelClass: 'SECOND_CLASS',
        discountType: 'NO_DISCOUNT',
      },
      fareOptions: {
        isInternationalBookable: false,
        isInternational: false,
        isEticketBuyable: true,
        isPossibleWithOvChipkaart: true,
        isTotalPriceUnknown: false,
      },
      type: 'NS',
      shareUrl: {
        uri: 'https://www.ns.nl/rpx?ctx=arnu%7CfromLocation%3D52.445937%2C4.81496%7CtoLocation%3D52.367926%2C4.882755%7CplannedFromTime%3D2022-04-11T23%3A21%3A00%2B02%3A00%7CoriginWalk%3Dtrue%7CdestinationWalk%3Dtrue%7CplannedArrivalTime%3D2022-04-12T00%3A09%3A00%2B02%3A00%7CyearCard%3Dfalse%7CexcludeHighSpeedTrains%3Dfalse%7CsearchForAccessibleTrip%3Dfalse',
      },
      realtime: true,
      routeId: '=KRkakyWBdA==',
      registerJourney: {
        url: 'https://treinwijzer.ns.nl/idp/login?ctxRecon=arnu%7CfromLocation%3D52.445937%2C4.81496%7CtoLocation%3D52.367926%2C4.882755%7CplannedFromTime%3D2022-04-11T23%3A21%3A00%2B02%3A00%7CoriginWalk%3Dtrue%7CdestinationWalk%3Dtrue%7CplannedArrivalTime%3D2022-04-12T00%3A09%3A00%2B02%3A00%7CyearCard%3Dfalse%7CexcludeHighSpeedTrains%3Dfalse%7CsearchForAccessibleTrip%3Dfalse&dateTime=2022-04-11T22%3A58%3A43.964582%2B02%3A00&searchForArrival=false&excludeHighSpeedTrains=false&localTrainsOnly=false&yearCard=false&searchForAccessibleTrip=false&lang=nl&travelAssistance=false',
        searchUrl:
          'https://treinwijzer.ns.nl/idp/login?search=true&dateTime=2022-04-11T22%3A58%3A43.964582%2B02%3A00&searchForArrival=false&excludeHighSpeedTrains=false&localTrainsOnly=false&yearCard=false&searchForAccessibleTrip=false&lang=nl&travelAssistance=false',
        status: 'REGISTRATION_POSSIBLE',
        bicycleReservationRequired: false,
        availability: {
          seats: true,
          numberOfSeats: 522,
          bicycle: true,
          numberOfBicyclePlaces: 8,
        },
      },
    },
    {
      idx: 3,
      uid: 'arnu|fromLocation=52.445937,4.81496|toLocation=52.367926,4.882755|plannedFromTime=2022-04-11T23:51:00+02:00|originWalk=true|destinationWalk=true|plannedArrivalTime=2022-04-12T00:39:00+02:00|yearCard=false|excludeHighSpeedTrains=false|searchForAccessibleTrip=false',
      ctxRecon:
        'arnu|fromLocation=52.445937,4.81496|toLocation=52.367926,4.882755|plannedFromTime=2022-04-11T23:51:00+02:00|originWalk=true|destinationWalk=true|plannedArrivalTime=2022-04-12T00:39:00+02:00|yearCard=false|excludeHighSpeedTrains=false|searchForAccessibleTrip=false',
      plannedDurationInMinutes: 48,
      actualDurationInMinutes: 48,
      transfers: 0,
      status: 'NORMAL',
      messages: [],
      legs: [
        {
          idx: '0',
          travelType: 'WALK',
          cancelled: false,
          changePossible: true,
          alternativeTransport: false,
          origin: {
            name: '',
            lng: 4.81496,
            lat: 52.445937,
            type: 'ADDRESS',
            plannedTimeZoneOffset: 120,
            plannedDateTime: '2022-04-11T23:51:00+0200',
            checkinStatus: 'NOTHING',
            notes: [],
          },
          destination: {
            name: 'Zaandam',
            lng: 4.81361103057861,
            lat: 52.4388885498047,
            countryCode: 'NL',
            uicCode: '8400731',
            type: 'STATION',
            plannedTimeZoneOffset: 120,
            plannedDateTime: '2022-04-12T00:04:00+0200',
            checkinStatus: 'NOTHING',
            notes: [],
          },
          product: {
            type: 'WALK',
          },
          messages: [],
          stops: [
            {
              name: '',
              lat: 52.445937,
              lng: 4.81496,
              notes: [],
              routeIdx: 0,
              plannedDepartureDateTime: '2022-04-11T23:51:00+0200',
              plannedDepartureTimeZoneOffset: 120,
              cancelled: false,
              borderStop: false,
              passing: false,
            },
            {
              uicCode: '8400731',
              name: 'Zaandam',
              lat: 52.4388885498047,
              lng: 4.81361103057861,
              countryCode: 'NL',
              notes: [],
              routeIdx: 1,
              plannedArrivalDateTime: '2022-04-12T00:04:00+0200',
              plannedArrivalTimeZoneOffset: 120,
              cancelled: false,
              borderStop: false,
              passing: false,
            },
          ],
          shorterStock: false,
          reachable: true,
          plannedDurationInMinutes: 13,
        },
        {
          idx: '1',
          name: 'SPR 4093',
          travelType: 'PUBLIC_TRANSIT',
          direction: 'Amsterdam Centraal',
          cancelled: false,
          changePossible: true,
          alternativeTransport: false,
          journeyDetailRef:
            'HARP_S2S-2|#VN#1#ST#1649241339#PI#0#ZI#441334#TA#0#DA#110422#1S#1100806#1T#2348#LS#1100915#LT#10017#PU#784#RT#1#CA#SPR#ZE#4093#ZB#SPR 4093#PC#3#FR#1100806#FT#2348#TO#1100915#TT#10017#',
          origin: {
            name: 'Zaandam',
            lng: 4.81361103057861,
            lat: 52.4388885498047,
            countryCode: 'NL',
            uicCode: '8400731',
            type: 'STATION',
            plannedTimeZoneOffset: 120,
            plannedDateTime: '2022-04-12T00:05:00+0200',
            plannedTrack: '5',
            actualTrack: '5',
            checkinStatus: 'CHECKIN',
            notes: [],
          },
          destination: {
            name: 'Amsterdam Centraal',
            lng: 4.90027761459351,
            lat: 52.3788871765137,
            countryCode: 'NL',
            uicCode: '8400058',
            type: 'STATION',
            plannedTimeZoneOffset: 120,
            plannedDateTime: '2022-04-12T00:17:00+0200',
            plannedTrack: '5',
            actualTrack: '5',
            exitSide: 'RIGHT',
            checkinStatus: 'CHECKOUT',
            notes: [],
          },
          product: {
            number: '4093',
            categoryCode: 'SPR',
            shortCategoryName: 'SPR',
            longCategoryName: 'Sprinter',
            operatorCode: 'ns',
            operatorName: 'NS',
            operatorAdministrativeCode: 100,
            type: 'TRAIN',
            displayName: 'NS Sprinter',
          },
          messages: [],
          stops: [
            {
              uicCode: '8400731',
              name: 'Zaandam',
              lat: 52.4388885498047,
              lng: 4.81361103057861,
              countryCode: 'NL',
              notes: [],
              routeIdx: 0,
              plannedDepartureDateTime: '2022-04-12T00:05:00+0200',
              plannedDepartureTimeZoneOffset: 120,
              actualDepartureTrack: '5',
              plannedDepartureTrack: '5',
              plannedArrivalTrack: '5',
              actualArrivalTrack: '5',
              cancelled: false,
              borderStop: false,
              passing: false,
            },
            {
              uicCode: '8400059',
              name: 'Amsterdam Sloterdijk',
              lat: 52.3888893127441,
              lng: 4.83777761459351,
              countryCode: 'NL',
              notes: [],
              routeIdx: 1,
              plannedDepartureDateTime: '2022-04-12T00:11:00+0200',
              plannedDepartureTimeZoneOffset: 120,
              plannedArrivalDateTime: '2022-04-12T00:11:00+0200',
              plannedArrivalTimeZoneOffset: 120,
              actualDepartureTrack: '6',
              plannedDepartureTrack: '6',
              plannedArrivalTrack: '6',
              actualArrivalTrack: '6',
              cancelled: false,
              borderStop: false,
              passing: false,
            },
            {
              uicCode: '8400058',
              name: 'Amsterdam Centraal',
              lat: 52.3788871765137,
              lng: 4.90027761459351,
              countryCode: 'NL',
              notes: [],
              routeIdx: 2,
              plannedArrivalDateTime: '2022-04-12T00:17:00+0200',
              plannedArrivalTimeZoneOffset: 120,
              actualDepartureTrack: '5',
              plannedDepartureTrack: '5',
              plannedArrivalTrack: '5',
              actualArrivalTrack: '5',
              cancelled: false,
              borderStop: false,
              passing: false,
            },
          ],
          crowdForecast: 'LOW',
          punctuality: 92.3,
          shorterStock: false,
          journeyDetail: [
            {
              type: 'TRAIN_XML',
              link: {
                uri: '/api/v2/journey?id=HARP_S2S-2|#VN#1#ST#1649241339#PI#0#ZI#441334#TA#0#DA#110422#1S#1100806#1T#2348#LS#1100915#LT#10017#PU#784#RT#1#CA#SPR#ZE#4093#ZB#SPR 4093#PC#3#FR#1100806#FT#2348#TO#1100915#TT#10017#&train=4093&datetime=2022-04-12T00:05:00+02:00',
              },
            },
          ],
          reachable: true,
          plannedDurationInMinutes: 12,
        },
        {
          idx: '2',
          travelType: 'WALK',
          cancelled: false,
          changePossible: true,
          alternativeTransport: false,
          origin: {
            name: 'Amsterdam Centraal',
            lng: 4.90027761459351,
            lat: 52.3788871765137,
            countryCode: 'NL',
            uicCode: '8400058',
            type: 'STATION',
            plannedTimeZoneOffset: 120,
            plannedDateTime: '2022-04-12T00:18:00+0200',
            checkinStatus: 'NOTHING',
            notes: [],
          },
          destination: {
            name: '',
            lng: 4.882755,
            lat: 52.367926,
            type: 'ADDRESS',
            plannedTimeZoneOffset: 120,
            plannedDateTime: '2022-04-12T00:39:00+0200',
            checkinStatus: 'NOTHING',
            notes: [],
          },
          product: {
            type: 'WALK',
          },
          messages: [],
          stops: [
            {
              uicCode: '8400058',
              name: 'Amsterdam Centraal',
              lat: 52.3788871765137,
              lng: 4.90027761459351,
              countryCode: 'NL',
              notes: [],
              routeIdx: 0,
              plannedDepartureDateTime: '2022-04-12T00:18:00+0200',
              plannedDepartureTimeZoneOffset: 120,
              cancelled: false,
              borderStop: false,
              passing: false,
            },
            {
              name: '',
              lat: 52.367926,
              lng: 4.882755,
              notes: [],
              routeIdx: 1,
              plannedArrivalDateTime: '2022-04-12T00:39:00+0200',
              plannedArrivalTimeZoneOffset: 120,
              cancelled: false,
              borderStop: false,
              passing: false,
            },
          ],
          shorterStock: false,
          reachable: true,
          plannedDurationInMinutes: 21,
        },
      ],
      crowdForecast: 'LOW',
      punctuality: 92.3,
      optimal: false,
      fareRoute: {
        routeId: '=KRkakyaBdA==',
        origin: {
          varCode: 731,
          name: 'Zaandam',
        },
        destination: {
          varCode: 58,
          name: 'Amsterdam Centraal',
        },
      },
      fares: [
        {
          priceInCents: 484,
          product: 'OVCHIPKAART_ENKELE_REIS',
          travelClass: 'FIRST_CLASS',
          discountType: 'NO_DISCOUNT',
        },
        {
          priceInCents: 290,
          product: 'OVCHIPKAART_ENKELE_REIS',
          travelClass: 'SECOND_CLASS',
          discountType: 'NO_DISCOUNT',
        },
        {
          priceInCents: 387,
          product: 'OVCHIPKAART_ENKELE_REIS',
          travelClass: 'FIRST_CLASS',
          discountType: 'DISCOUNT_20_PERCENT',
        },
        {
          priceInCents: 232,
          product: 'OVCHIPKAART_ENKELE_REIS',
          travelClass: 'SECOND_CLASS',
          discountType: 'DISCOUNT_20_PERCENT',
        },
        {
          priceInCents: 290,
          product: 'OVCHIPKAART_ENKELE_REIS',
          travelClass: 'FIRST_CLASS',
          discountType: 'DISCOUNT_40_PERCENT',
        },
        {
          priceInCents: 174,
          product: 'OVCHIPKAART_ENKELE_REIS',
          travelClass: 'SECOND_CLASS',
          discountType: 'DISCOUNT_40_PERCENT',
        },
        {
          priceInCents: 968,
          product: 'OVCHIPKAART_RETOUR',
          travelClass: 'FIRST_CLASS',
          discountType: 'NO_DISCOUNT',
        },
        {
          priceInCents: 580,
          product: 'OVCHIPKAART_RETOUR',
          travelClass: 'SECOND_CLASS',
          discountType: 'NO_DISCOUNT',
        },
        {
          priceInCents: 774,
          product: 'OVCHIPKAART_RETOUR',
          travelClass: 'FIRST_CLASS',
          discountType: 'DISCOUNT_20_PERCENT',
        },
        {
          priceInCents: 464,
          product: 'OVCHIPKAART_RETOUR',
          travelClass: 'SECOND_CLASS',
          discountType: 'DISCOUNT_20_PERCENT',
        },
        {
          priceInCents: 580,
          product: 'OVCHIPKAART_RETOUR',
          travelClass: 'FIRST_CLASS',
          discountType: 'DISCOUNT_40_PERCENT',
        },
        {
          priceInCents: 348,
          product: 'OVCHIPKAART_RETOUR',
          travelClass: 'SECOND_CLASS',
          discountType: 'DISCOUNT_40_PERCENT',
        },
        {
          priceInCents: 14970,
          product: 'TRAJECT_VRIJ_MAAND',
          travelClass: 'FIRST_CLASS',
          discountType: 'NO_DISCOUNT',
        },
        {
          priceInCents: 8860,
          product: 'TRAJECT_VRIJ_MAAND',
          travelClass: 'SECOND_CLASS',
          discountType: 'NO_DISCOUNT',
        },
        {
          priceInCents: 12240,
          product: 'TRAJECT_VRIJ_JAAR',
          travelClass: 'FIRST_CLASS',
          discountType: 'NO_DISCOUNT',
        },
        {
          priceInCents: 7240,
          product: 'TRAJECT_VRIJ_JAAR',
          travelClass: 'SECOND_CLASS',
          discountType: 'NO_DISCOUNT',
        },
        {
          priceInCents: 146888,
          product: 'BUSINESS_CARD_TRAJECT_VRIJ_JAAR',
          travelClass: 'FIRST_CLASS',
          discountType: 'NO_DISCOUNT',
        },
        {
          priceInCents: 86851,
          product: 'BUSINESS_CARD_TRAJECT_VRIJ_JAAR',
          travelClass: 'SECOND_CLASS',
          discountType: 'NO_DISCOUNT',
        },
      ],
      fareLegs: [
        {
          origin: {
            name: 'Zaandam',
            lng: 4.81361103057861,
            lat: 52.4388885498047,
            countryCode: 'NL',
            uicCode: '8400731',
            type: 'STATION',
          },
          destination: {
            name: 'Amsterdam Centraal',
            lng: 4.90027761459351,
            lat: 52.3788871765137,
            countryCode: 'NL',
            uicCode: '8400058',
            type: 'STATION',
          },
          operator: 'NS',
          productTypes: ['TRAIN'],
          fares: [
            {
              priceInCents: 290,
              priceInCentsExcludingSupplement: 290,
              supplementInCents: 0,
              buyableTicketSupplementPriceInCents: 0,
              product: 'OVCHIPKAART_ENKELE_REIS',
              travelClass: 'SECOND_CLASS',
              discountType: 'NO_DISCOUNT',
            },
          ],
        },
      ],
      productFare: {
        priceInCents: 290,
        priceInCentsExcludingSupplement: 290,
        buyableTicketPriceInCents: 290,
        buyableTicketPriceInCentsExcludingSupplement: 290,
        product: 'OVCHIPKAART_ENKELE_REIS',
        travelClass: 'SECOND_CLASS',
        discountType: 'NO_DISCOUNT',
      },
      fareOptions: {
        isInternationalBookable: false,
        isInternational: false,
        isEticketBuyable: true,
        isPossibleWithOvChipkaart: true,
        isTotalPriceUnknown: false,
      },
      type: 'NS',
      shareUrl: {
        uri: 'https://www.ns.nl/rpx?ctx=arnu%7CfromLocation%3D52.445937%2C4.81496%7CtoLocation%3D52.367926%2C4.882755%7CplannedFromTime%3D2022-04-11T23%3A51%3A00%2B02%3A00%7CoriginWalk%3Dtrue%7CdestinationWalk%3Dtrue%7CplannedArrivalTime%3D2022-04-12T00%3A39%3A00%2B02%3A00%7CyearCard%3Dfalse%7CexcludeHighSpeedTrains%3Dfalse%7CsearchForAccessibleTrip%3Dfalse',
      },
      realtime: true,
      routeId: '=KRkakyaBdA==',
      registerJourney: {
        url: 'https://treinwijzer.ns.nl/idp/login?ctxRecon=arnu%7CfromLocation%3D52.445937%2C4.81496%7CtoLocation%3D52.367926%2C4.882755%7CplannedFromTime%3D2022-04-11T23%3A51%3A00%2B02%3A00%7CoriginWalk%3Dtrue%7CdestinationWalk%3Dtrue%7CplannedArrivalTime%3D2022-04-12T00%3A39%3A00%2B02%3A00%7CyearCard%3Dfalse%7CexcludeHighSpeedTrains%3Dfalse%7CsearchForAccessibleTrip%3Dfalse&dateTime=2022-04-11T22%3A58%3A43.964582%2B02%3A00&searchForArrival=false&excludeHighSpeedTrains=false&localTrainsOnly=false&yearCard=false&searchForAccessibleTrip=false&lang=nl&travelAssistance=false',
        searchUrl:
          'https://treinwijzer.ns.nl/idp/login?search=true&dateTime=2022-04-11T22%3A58%3A43.964582%2B02%3A00&searchForArrival=false&excludeHighSpeedTrains=false&localTrainsOnly=false&yearCard=false&searchForAccessibleTrip=false&lang=nl&travelAssistance=false',
        status: 'REGISTRATION_POSSIBLE',
        bicycleReservationRequired: false,
        availability: {
          seats: true,
          numberOfSeats: 522,
          bicycle: true,
          numberOfBicyclePlaces: 8,
        },
      },
    },
    {
      idx: 4,
      uid: 'arnu|fromLocation=52.445937,4.81496|toLocation=52.367926,4.882755|plannedFromTime=2022-04-11T23:54:00+02:00|originWalk=true|destinationWalk=true|plannedArrivalTime=2022-04-12T00:43:00+02:00|yearCard=false|excludeHighSpeedTrains=false|searchForAccessibleTrip=false',
      ctxRecon:
        'arnu|fromLocation=52.445937,4.81496|toLocation=52.367926,4.882755|plannedFromTime=2022-04-11T23:54:00+02:00|originWalk=true|destinationWalk=true|plannedArrivalTime=2022-04-12T00:43:00+02:00|yearCard=false|excludeHighSpeedTrains=false|searchForAccessibleTrip=false',
      plannedDurationInMinutes: 49,
      actualDurationInMinutes: 49,
      transfers: 0,
      status: 'NORMAL',
      messages: [],
      legs: [
        {
          idx: '0',
          travelType: 'WALK',
          cancelled: false,
          changePossible: true,
          alternativeTransport: false,
          origin: {
            name: '',
            lng: 4.81496,
            lat: 52.445937,
            type: 'ADDRESS',
            plannedTimeZoneOffset: 120,
            plannedDateTime: '2022-04-11T23:54:00+0200',
            checkinStatus: 'NOTHING',
            notes: [],
          },
          destination: {
            name: 'Zaandam',
            lng: 4.81361103057861,
            lat: 52.4388885498047,
            countryCode: 'NL',
            uicCode: '8400731',
            type: 'STATION',
            plannedTimeZoneOffset: 120,
            plannedDateTime: '2022-04-12T00:07:00+0200',
            checkinStatus: 'NOTHING',
            notes: [],
          },
          product: {
            type: 'WALK',
          },
          messages: [],
          stops: [
            {
              name: '',
              lat: 52.445937,
              lng: 4.81496,
              notes: [],
              routeIdx: 0,
              plannedDepartureDateTime: '2022-04-11T23:54:00+0200',
              plannedDepartureTimeZoneOffset: 120,
              cancelled: false,
              borderStop: false,
              passing: false,
            },
            {
              uicCode: '8400731',
              name: 'Zaandam',
              lat: 52.4388885498047,
              lng: 4.81361103057861,
              countryCode: 'NL',
              notes: [],
              routeIdx: 1,
              plannedArrivalDateTime: '2022-04-12T00:07:00+0200',
              plannedArrivalTimeZoneOffset: 120,
              cancelled: false,
              borderStop: false,
              passing: false,
            },
          ],
          shorterStock: false,
          reachable: true,
          plannedDurationInMinutes: 13,
        },
        {
          idx: '1',
          name: 'IC 3091',
          travelType: 'PUBLIC_TRANSIT',
          direction: 'Nijmegen',
          cancelled: false,
          changePossible: true,
          alternativeTransport: false,
          journeyDetailRef:
            'HARP_S2S-2|#VN#1#ST#1649241339#PI#0#ZI#439776#TA#0#DA#110422#1S#1101028#1T#2304#LS#1100865#LT#10149#PU#784#RT#1#CA#IC#ZE#3091#ZB#IC 3091 #PC#1#FR#1101028#FT#2304#TO#1100865#TT#10149#',
          origin: {
            name: 'Zaandam',
            lng: 4.81361103057861,
            lat: 52.4388885498047,
            countryCode: 'NL',
            uicCode: '8400731',
            type: 'STATION',
            plannedTimeZoneOffset: 120,
            plannedDateTime: '2022-04-12T00:08:00+0200',
            plannedTrack: '4',
            actualTrack: '4',
            checkinStatus: 'CHECKIN',
            notes: [],
          },
          destination: {
            name: 'Amsterdam Centraal',
            lng: 4.90027761459351,
            lat: 52.3788871765137,
            countryCode: 'NL',
            uicCode: '8400058',
            type: 'STATION',
            plannedTimeZoneOffset: 120,
            plannedDateTime: '2022-04-12T00:21:00+0200',
            plannedTrack: '2b',
            actualTrack: '2b',
            exitSide: 'RIGHT',
            checkinStatus: 'CHECKOUT',
            notes: [],
          },
          product: {
            number: '3091',
            categoryCode: 'IC',
            shortCategoryName: 'IC',
            longCategoryName: 'Intercity',
            operatorCode: 'ns',
            operatorName: 'NS',
            operatorAdministrativeCode: 100,
            type: 'TRAIN',
            displayName: 'NS Intercity',
          },
          messages: [],
          stops: [
            {
              uicCode: '8400731',
              name: 'Zaandam',
              lat: 52.4388885498047,
              lng: 4.81361103057861,
              countryCode: 'NL',
              notes: [],
              routeIdx: 0,
              plannedDepartureDateTime: '2022-04-12T00:08:00+0200',
              plannedDepartureTimeZoneOffset: 120,
              actualDepartureTrack: '4',
              plannedDepartureTrack: '4',
              plannedArrivalTrack: '4',
              actualArrivalTrack: '4',
              cancelled: false,
              borderStop: false,
              passing: false,
            },
            {
              uicCode: '8400059',
              name: 'Amsterdam Sloterdijk',
              lat: 52.3888893127441,
              lng: 4.83777761459351,
              countryCode: 'NL',
              notes: [],
              routeIdx: 1,
              plannedDepartureDateTime: '2022-04-12T00:15:00+0200',
              plannedDepartureTimeZoneOffset: 120,
              plannedArrivalDateTime: '2022-04-12T00:15:00+0200',
              plannedArrivalTimeZoneOffset: 120,
              actualDepartureTrack: '5',
              plannedDepartureTrack: '5',
              plannedArrivalTrack: '5',
              actualArrivalTrack: '5',
              cancelled: false,
              borderStop: false,
              passing: false,
            },
            {
              uicCode: '8400058',
              name: 'Amsterdam Centraal',
              lat: 52.3788871765137,
              lng: 4.90027761459351,
              countryCode: 'NL',
              notes: [],
              routeIdx: 2,
              plannedArrivalDateTime: '2022-04-12T00:21:00+0200',
              plannedArrivalTimeZoneOffset: 120,
              actualDepartureTrack: '2b',
              plannedDepartureTrack: '2b',
              plannedArrivalTrack: '2b',
              actualArrivalTrack: '2b',
              cancelled: false,
              borderStop: false,
              passing: false,
            },
          ],
          crowdForecast: 'LOW',
          punctuality: 100,
          shorterStock: false,
          journeyDetail: [
            {
              type: 'TRAIN_XML',
              link: {
                uri: '/api/v2/journey?id=HARP_S2S-2|#VN#1#ST#1649241339#PI#0#ZI#439776#TA#0#DA#110422#1S#1101028#1T#2304#LS#1100865#LT#10149#PU#784#RT#1#CA#IC#ZE#3091#ZB#IC 3091 #PC#1#FR#1101028#FT#2304#TO#1100865#TT#10149#&train=3091&datetime=2022-04-12T00:08:00+02:00',
              },
            },
          ],
          reachable: true,
          plannedDurationInMinutes: 13,
        },
        {
          idx: '2',
          travelType: 'WALK',
          cancelled: false,
          changePossible: true,
          alternativeTransport: false,
          origin: {
            name: 'Amsterdam Centraal',
            lng: 4.90027761459351,
            lat: 52.3788871765137,
            countryCode: 'NL',
            uicCode: '8400058',
            type: 'STATION',
            plannedTimeZoneOffset: 120,
            plannedDateTime: '2022-04-12T00:22:00+0200',
            checkinStatus: 'NOTHING',
            notes: [],
          },
          destination: {
            name: '',
            lng: 4.882755,
            lat: 52.367926,
            type: 'ADDRESS',
            plannedTimeZoneOffset: 120,
            plannedDateTime: '2022-04-12T00:43:00+0200',
            checkinStatus: 'NOTHING',
            notes: [],
          },
          product: {
            type: 'WALK',
          },
          messages: [],
          stops: [
            {
              uicCode: '8400058',
              name: 'Amsterdam Centraal',
              lat: 52.3788871765137,
              lng: 4.90027761459351,
              countryCode: 'NL',
              notes: [],
              routeIdx: 0,
              plannedDepartureDateTime: '2022-04-12T00:22:00+0200',
              plannedDepartureTimeZoneOffset: 120,
              cancelled: false,
              borderStop: false,
              passing: false,
            },
            {
              name: '',
              lat: 52.367926,
              lng: 4.882755,
              notes: [],
              routeIdx: 1,
              plannedArrivalDateTime: '2022-04-12T00:43:00+0200',
              plannedArrivalTimeZoneOffset: 120,
              cancelled: false,
              borderStop: false,
              passing: false,
            },
          ],
          shorterStock: false,
          reachable: true,
          plannedDurationInMinutes: 21,
        },
      ],
      crowdForecast: 'LOW',
      punctuality: 100,
      optimal: false,
      fareRoute: {
        routeId: '=KRkakyaBdA==',
        origin: {
          varCode: 731,
          name: 'Zaandam',
        },
        destination: {
          varCode: 58,
          name: 'Amsterdam Centraal',
        },
      },
      fares: [
        {
          priceInCents: 484,
          product: 'OVCHIPKAART_ENKELE_REIS',
          travelClass: 'FIRST_CLASS',
          discountType: 'NO_DISCOUNT',
        },
        {
          priceInCents: 290,
          product: 'OVCHIPKAART_ENKELE_REIS',
          travelClass: 'SECOND_CLASS',
          discountType: 'NO_DISCOUNT',
        },
        {
          priceInCents: 387,
          product: 'OVCHIPKAART_ENKELE_REIS',
          travelClass: 'FIRST_CLASS',
          discountType: 'DISCOUNT_20_PERCENT',
        },
        {
          priceInCents: 232,
          product: 'OVCHIPKAART_ENKELE_REIS',
          travelClass: 'SECOND_CLASS',
          discountType: 'DISCOUNT_20_PERCENT',
        },
        {
          priceInCents: 290,
          product: 'OVCHIPKAART_ENKELE_REIS',
          travelClass: 'FIRST_CLASS',
          discountType: 'DISCOUNT_40_PERCENT',
        },
        {
          priceInCents: 174,
          product: 'OVCHIPKAART_ENKELE_REIS',
          travelClass: 'SECOND_CLASS',
          discountType: 'DISCOUNT_40_PERCENT',
        },
        {
          priceInCents: 968,
          product: 'OVCHIPKAART_RETOUR',
          travelClass: 'FIRST_CLASS',
          discountType: 'NO_DISCOUNT',
        },
        {
          priceInCents: 580,
          product: 'OVCHIPKAART_RETOUR',
          travelClass: 'SECOND_CLASS',
          discountType: 'NO_DISCOUNT',
        },
        {
          priceInCents: 774,
          product: 'OVCHIPKAART_RETOUR',
          travelClass: 'FIRST_CLASS',
          discountType: 'DISCOUNT_20_PERCENT',
        },
        {
          priceInCents: 464,
          product: 'OVCHIPKAART_RETOUR',
          travelClass: 'SECOND_CLASS',
          discountType: 'DISCOUNT_20_PERCENT',
        },
        {
          priceInCents: 580,
          product: 'OVCHIPKAART_RETOUR',
          travelClass: 'FIRST_CLASS',
          discountType: 'DISCOUNT_40_PERCENT',
        },
        {
          priceInCents: 348,
          product: 'OVCHIPKAART_RETOUR',
          travelClass: 'SECOND_CLASS',
          discountType: 'DISCOUNT_40_PERCENT',
        },
        {
          priceInCents: 14970,
          product: 'TRAJECT_VRIJ_MAAND',
          travelClass: 'FIRST_CLASS',
          discountType: 'NO_DISCOUNT',
        },
        {
          priceInCents: 8860,
          product: 'TRAJECT_VRIJ_MAAND',
          travelClass: 'SECOND_CLASS',
          discountType: 'NO_DISCOUNT',
        },
        {
          priceInCents: 12240,
          product: 'TRAJECT_VRIJ_JAAR',
          travelClass: 'FIRST_CLASS',
          discountType: 'NO_DISCOUNT',
        },
        {
          priceInCents: 7240,
          product: 'TRAJECT_VRIJ_JAAR',
          travelClass: 'SECOND_CLASS',
          discountType: 'NO_DISCOUNT',
        },
        {
          priceInCents: 146888,
          product: 'BUSINESS_CARD_TRAJECT_VRIJ_JAAR',
          travelClass: 'FIRST_CLASS',
          discountType: 'NO_DISCOUNT',
        },
        {
          priceInCents: 86851,
          product: 'BUSINESS_CARD_TRAJECT_VRIJ_JAAR',
          travelClass: 'SECOND_CLASS',
          discountType: 'NO_DISCOUNT',
        },
      ],
      fareLegs: [
        {
          origin: {
            name: 'Zaandam',
            lng: 4.81361103057861,
            lat: 52.4388885498047,
            countryCode: 'NL',
            uicCode: '8400731',
            type: 'STATION',
          },
          destination: {
            name: 'Amsterdam Centraal',
            lng: 4.90027761459351,
            lat: 52.3788871765137,
            countryCode: 'NL',
            uicCode: '8400058',
            type: 'STATION',
          },
          operator: 'NS',
          productTypes: ['TRAIN'],
          fares: [
            {
              priceInCents: 290,
              priceInCentsExcludingSupplement: 290,
              supplementInCents: 0,
              buyableTicketSupplementPriceInCents: 0,
              product: 'OVCHIPKAART_ENKELE_REIS',
              travelClass: 'SECOND_CLASS',
              discountType: 'NO_DISCOUNT',
            },
          ],
        },
      ],
      productFare: {
        priceInCents: 290,
        priceInCentsExcludingSupplement: 290,
        buyableTicketPriceInCents: 290,
        buyableTicketPriceInCentsExcludingSupplement: 290,
        product: 'OVCHIPKAART_ENKELE_REIS',
        travelClass: 'SECOND_CLASS',
        discountType: 'NO_DISCOUNT',
      },
      fareOptions: {
        isInternationalBookable: false,
        isInternational: false,
        isEticketBuyable: true,
        isPossibleWithOvChipkaart: true,
        isTotalPriceUnknown: false,
      },
      type: 'NS',
      shareUrl: {
        uri: 'https://www.ns.nl/rpx?ctx=arnu%7CfromLocation%3D52.445937%2C4.81496%7CtoLocation%3D52.367926%2C4.882755%7CplannedFromTime%3D2022-04-11T23%3A54%3A00%2B02%3A00%7CoriginWalk%3Dtrue%7CdestinationWalk%3Dtrue%7CplannedArrivalTime%3D2022-04-12T00%3A43%3A00%2B02%3A00%7CyearCard%3Dfalse%7CexcludeHighSpeedTrains%3Dfalse%7CsearchForAccessibleTrip%3Dfalse',
      },
      realtime: true,
      routeId: '=KRkakyaBdA==',
      registerJourney: {
        url: 'https://treinwijzer.ns.nl/idp/login?ctxRecon=arnu%7CfromLocation%3D52.445937%2C4.81496%7CtoLocation%3D52.367926%2C4.882755%7CplannedFromTime%3D2022-04-11T23%3A54%3A00%2B02%3A00%7CoriginWalk%3Dtrue%7CdestinationWalk%3Dtrue%7CplannedArrivalTime%3D2022-04-12T00%3A43%3A00%2B02%3A00%7CyearCard%3Dfalse%7CexcludeHighSpeedTrains%3Dfalse%7CsearchForAccessibleTrip%3Dfalse&dateTime=2022-04-11T22%3A58%3A43.964582%2B02%3A00&searchForArrival=false&excludeHighSpeedTrains=false&localTrainsOnly=false&yearCard=false&searchForAccessibleTrip=false&lang=nl&travelAssistance=false',
        searchUrl:
          'https://treinwijzer.ns.nl/idp/login?search=true&dateTime=2022-04-11T22%3A58%3A43.964582%2B02%3A00&searchForArrival=false&excludeHighSpeedTrains=false&localTrainsOnly=false&yearCard=false&searchForAccessibleTrip=false&lang=nl&travelAssistance=false',
        status: 'REGISTRATION_POSSIBLE',
        bicycleReservationRequired: false,
        availability: {
          seats: true,
          numberOfSeats: 597,
          bicycle: true,
          numberOfBicyclePlaces: 9,
        },
      },
    },
    {
      idx: 5,
      uid: 'arnu|fromLocation=52.445937,4.81496|toLocation=52.367926,4.882755|plannedFromTime=2022-04-12T00:19:00+02:00|originWalk=true|destinationWalk=true|plannedArrivalTime=2022-04-12T01:07:00+02:00|yearCard=false|excludeHighSpeedTrains=false|searchForAccessibleTrip=false',
      ctxRecon:
        'arnu|fromLocation=52.445937,4.81496|toLocation=52.367926,4.882755|plannedFromTime=2022-04-12T00:19:00+02:00|originWalk=true|destinationWalk=true|plannedArrivalTime=2022-04-12T01:07:00+02:00|yearCard=false|excludeHighSpeedTrains=false|searchForAccessibleTrip=false',
      plannedDurationInMinutes: 48,
      actualDurationInMinutes: 48,
      transfers: 0,
      status: 'NORMAL',
      messages: [],
      legs: [
        {
          idx: '0',
          travelType: 'WALK',
          cancelled: false,
          changePossible: true,
          alternativeTransport: false,
          origin: {
            name: '',
            lng: 4.81496,
            lat: 52.445937,
            type: 'ADDRESS',
            plannedTimeZoneOffset: 120,
            plannedDateTime: '2022-04-12T00:19:00+0200',
            checkinStatus: 'NOTHING',
            notes: [],
          },
          destination: {
            name: 'Zaandam',
            lng: 4.81361103057861,
            lat: 52.4388885498047,
            countryCode: 'NL',
            uicCode: '8400731',
            type: 'STATION',
            plannedTimeZoneOffset: 120,
            plannedDateTime: '2022-04-12T00:32:00+0200',
            checkinStatus: 'NOTHING',
            notes: [],
          },
          product: {
            type: 'WALK',
          },
          messages: [],
          stops: [
            {
              name: '',
              lat: 52.445937,
              lng: 4.81496,
              notes: [],
              routeIdx: 0,
              plannedDepartureDateTime: '2022-04-12T00:19:00+0200',
              plannedDepartureTimeZoneOffset: 120,
              cancelled: false,
              borderStop: false,
              passing: false,
            },
            {
              uicCode: '8400731',
              name: 'Zaandam',
              lat: 52.4388885498047,
              lng: 4.81361103057861,
              countryCode: 'NL',
              notes: [],
              routeIdx: 1,
              plannedArrivalDateTime: '2022-04-12T00:32:00+0200',
              plannedArrivalTimeZoneOffset: 120,
              cancelled: false,
              borderStop: false,
              passing: false,
            },
          ],
          shorterStock: false,
          reachable: true,
          plannedDurationInMinutes: 13,
        },
        {
          idx: '1',
          name: 'IC 2993',
          travelType: 'PUBLIC_TRANSIT',
          direction: 'Amsterdam Centraal',
          cancelled: false,
          changePossible: true,
          alternativeTransport: false,
          journeyDetailRef:
            'HARP_S2S-2|#VN#1#ST#1649241339#PI#0#ZI#439240#TA#0#DA#110422#1S#1101046#1T#2339#LS#1100850#LT#10045#PU#784#RT#1#CA#IC#ZE#2993#ZB#IC 2993 #PC#1#FR#1101046#FT#2339#TO#1100850#TT#10045#',
          origin: {
            name: 'Zaandam',
            lng: 4.81361103057861,
            lat: 52.4388885498047,
            countryCode: 'NL',
            uicCode: '8400731',
            type: 'STATION',
            plannedTimeZoneOffset: 120,
            plannedDateTime: '2022-04-12T00:33:00+0200',
            plannedTrack: '5',
            actualTrack: '5',
            checkinStatus: 'CHECKIN',
            notes: [],
          },
          destination: {
            name: 'Amsterdam Centraal',
            lng: 4.90027761459351,
            lat: 52.3788871765137,
            countryCode: 'NL',
            uicCode: '8400058',
            type: 'STATION',
            plannedTimeZoneOffset: 120,
            plannedDateTime: '2022-04-12T00:45:00+0200',
            plannedTrack: '4b',
            actualTrack: '4b',
            exitSide: 'LEFT',
            checkinStatus: 'CHECKOUT',
            notes: [],
          },
          product: {
            number: '2993',
            categoryCode: 'IC',
            shortCategoryName: 'IC',
            longCategoryName: 'Intercity',
            operatorCode: 'ns',
            operatorName: 'NS',
            operatorAdministrativeCode: 100,
            type: 'TRAIN',
            displayName: 'NS Intercity',
          },
          messages: [],
          stops: [
            {
              uicCode: '8400731',
              name: 'Zaandam',
              lat: 52.4388885498047,
              lng: 4.81361103057861,
              countryCode: 'NL',
              notes: [],
              routeIdx: 0,
              plannedDepartureDateTime: '2022-04-12T00:33:00+0200',
              plannedDepartureTimeZoneOffset: 120,
              actualDepartureTrack: '5',
              plannedDepartureTrack: '5',
              plannedArrivalTrack: '5',
              actualArrivalTrack: '5',
              cancelled: false,
              borderStop: false,
              passing: false,
            },
            {
              uicCode: '8400059',
              name: 'Amsterdam Sloterdijk',
              lat: 52.3888893127441,
              lng: 4.83777761459351,
              countryCode: 'NL',
              notes: [],
              routeIdx: 1,
              plannedDepartureDateTime: '2022-04-12T00:39:00+0200',
              plannedDepartureTimeZoneOffset: 120,
              plannedArrivalDateTime: '2022-04-12T00:39:00+0200',
              plannedArrivalTimeZoneOffset: 120,
              actualDepartureTrack: '6',
              plannedDepartureTrack: '6',
              plannedArrivalTrack: '6',
              actualArrivalTrack: '6',
              cancelled: false,
              borderStop: false,
              passing: false,
            },
            {
              uicCode: '8400058',
              name: 'Amsterdam Centraal',
              lat: 52.3788871765137,
              lng: 4.90027761459351,
              countryCode: 'NL',
              notes: [],
              routeIdx: 2,
              plannedArrivalDateTime: '2022-04-12T00:45:00+0200',
              plannedArrivalTimeZoneOffset: 120,
              actualDepartureTrack: '4b',
              plannedDepartureTrack: '4b',
              plannedArrivalTrack: '4b',
              actualArrivalTrack: '4b',
              cancelled: false,
              borderStop: false,
              passing: false,
            },
          ],
          crowdForecast: 'LOW',
          punctuality: 100,
          shorterStock: false,
          journeyDetail: [
            {
              type: 'TRAIN_XML',
              link: {
                uri: '/api/v2/journey?id=HARP_S2S-2|#VN#1#ST#1649241339#PI#0#ZI#439240#TA#0#DA#110422#1S#1101046#1T#2339#LS#1100850#LT#10045#PU#784#RT#1#CA#IC#ZE#2993#ZB#IC 2993 #PC#1#FR#1101046#FT#2339#TO#1100850#TT#10045#&train=2993&datetime=2022-04-12T00:33:00+02:00',
              },
            },
          ],
          reachable: true,
          plannedDurationInMinutes: 12,
        },
        {
          idx: '2',
          travelType: 'WALK',
          cancelled: false,
          changePossible: true,
          alternativeTransport: false,
          origin: {
            name: 'Amsterdam Centraal',
            lng: 4.90027761459351,
            lat: 52.3788871765137,
            countryCode: 'NL',
            uicCode: '8400058',
            type: 'STATION',
            plannedTimeZoneOffset: 120,
            plannedDateTime: '2022-04-12T00:46:00+0200',
            checkinStatus: 'NOTHING',
            notes: [],
          },
          destination: {
            name: '',
            lng: 4.882755,
            lat: 52.367926,
            type: 'ADDRESS',
            plannedTimeZoneOffset: 120,
            plannedDateTime: '2022-04-12T01:07:00+0200',
            checkinStatus: 'NOTHING',
            notes: [],
          },
          product: {
            type: 'WALK',
          },
          messages: [],
          stops: [
            {
              uicCode: '8400058',
              name: 'Amsterdam Centraal',
              lat: 52.3788871765137,
              lng: 4.90027761459351,
              countryCode: 'NL',
              notes: [],
              routeIdx: 0,
              plannedDepartureDateTime: '2022-04-12T00:46:00+0200',
              plannedDepartureTimeZoneOffset: 120,
              cancelled: false,
              borderStop: false,
              passing: false,
            },
            {
              name: '',
              lat: 52.367926,
              lng: 4.882755,
              notes: [],
              routeIdx: 1,
              plannedArrivalDateTime: '2022-04-12T01:07:00+0200',
              plannedArrivalTimeZoneOffset: 120,
              cancelled: false,
              borderStop: false,
              passing: false,
            },
          ],
          shorterStock: false,
          reachable: true,
          plannedDurationInMinutes: 21,
        },
      ],
      crowdForecast: 'LOW',
      punctuality: 100,
      optimal: false,
      fareRoute: {
        routeId: '=KRkakyaBdA==',
        origin: {
          varCode: 731,
          name: 'Zaandam',
        },
        destination: {
          varCode: 58,
          name: 'Amsterdam Centraal',
        },
      },
      fares: [
        {
          priceInCents: 484,
          product: 'OVCHIPKAART_ENKELE_REIS',
          travelClass: 'FIRST_CLASS',
          discountType: 'NO_DISCOUNT',
        },
        {
          priceInCents: 290,
          product: 'OVCHIPKAART_ENKELE_REIS',
          travelClass: 'SECOND_CLASS',
          discountType: 'NO_DISCOUNT',
        },
        {
          priceInCents: 387,
          product: 'OVCHIPKAART_ENKELE_REIS',
          travelClass: 'FIRST_CLASS',
          discountType: 'DISCOUNT_20_PERCENT',
        },
        {
          priceInCents: 232,
          product: 'OVCHIPKAART_ENKELE_REIS',
          travelClass: 'SECOND_CLASS',
          discountType: 'DISCOUNT_20_PERCENT',
        },
        {
          priceInCents: 290,
          product: 'OVCHIPKAART_ENKELE_REIS',
          travelClass: 'FIRST_CLASS',
          discountType: 'DISCOUNT_40_PERCENT',
        },
        {
          priceInCents: 174,
          product: 'OVCHIPKAART_ENKELE_REIS',
          travelClass: 'SECOND_CLASS',
          discountType: 'DISCOUNT_40_PERCENT',
        },
        {
          priceInCents: 968,
          product: 'OVCHIPKAART_RETOUR',
          travelClass: 'FIRST_CLASS',
          discountType: 'NO_DISCOUNT',
        },
        {
          priceInCents: 580,
          product: 'OVCHIPKAART_RETOUR',
          travelClass: 'SECOND_CLASS',
          discountType: 'NO_DISCOUNT',
        },
        {
          priceInCents: 774,
          product: 'OVCHIPKAART_RETOUR',
          travelClass: 'FIRST_CLASS',
          discountType: 'DISCOUNT_20_PERCENT',
        },
        {
          priceInCents: 464,
          product: 'OVCHIPKAART_RETOUR',
          travelClass: 'SECOND_CLASS',
          discountType: 'DISCOUNT_20_PERCENT',
        },
        {
          priceInCents: 580,
          product: 'OVCHIPKAART_RETOUR',
          travelClass: 'FIRST_CLASS',
          discountType: 'DISCOUNT_40_PERCENT',
        },
        {
          priceInCents: 348,
          product: 'OVCHIPKAART_RETOUR',
          travelClass: 'SECOND_CLASS',
          discountType: 'DISCOUNT_40_PERCENT',
        },
        {
          priceInCents: 14970,
          product: 'TRAJECT_VRIJ_MAAND',
          travelClass: 'FIRST_CLASS',
          discountType: 'NO_DISCOUNT',
        },
        {
          priceInCents: 8860,
          product: 'TRAJECT_VRIJ_MAAND',
          travelClass: 'SECOND_CLASS',
          discountType: 'NO_DISCOUNT',
        },
        {
          priceInCents: 12240,
          product: 'TRAJECT_VRIJ_JAAR',
          travelClass: 'FIRST_CLASS',
          discountType: 'NO_DISCOUNT',
        },
        {
          priceInCents: 7240,
          product: 'TRAJECT_VRIJ_JAAR',
          travelClass: 'SECOND_CLASS',
          discountType: 'NO_DISCOUNT',
        },
        {
          priceInCents: 146888,
          product: 'BUSINESS_CARD_TRAJECT_VRIJ_JAAR',
          travelClass: 'FIRST_CLASS',
          discountType: 'NO_DISCOUNT',
        },
        {
          priceInCents: 86851,
          product: 'BUSINESS_CARD_TRAJECT_VRIJ_JAAR',
          travelClass: 'SECOND_CLASS',
          discountType: 'NO_DISCOUNT',
        },
      ],
      fareLegs: [
        {
          origin: {
            name: 'Zaandam',
            lng: 4.81361103057861,
            lat: 52.4388885498047,
            countryCode: 'NL',
            uicCode: '8400731',
            type: 'STATION',
          },
          destination: {
            name: 'Amsterdam Centraal',
            lng: 4.90027761459351,
            lat: 52.3788871765137,
            countryCode: 'NL',
            uicCode: '8400058',
            type: 'STATION',
          },
          operator: 'NS',
          productTypes: ['TRAIN'],
          fares: [
            {
              priceInCents: 290,
              priceInCentsExcludingSupplement: 290,
              supplementInCents: 0,
              buyableTicketSupplementPriceInCents: 0,
              product: 'OVCHIPKAART_ENKELE_REIS',
              travelClass: 'SECOND_CLASS',
              discountType: 'NO_DISCOUNT',
            },
          ],
        },
      ],
      productFare: {
        priceInCents: 290,
        priceInCentsExcludingSupplement: 290,
        buyableTicketPriceInCents: 290,
        buyableTicketPriceInCentsExcludingSupplement: 290,
        product: 'OVCHIPKAART_ENKELE_REIS',
        travelClass: 'SECOND_CLASS',
        discountType: 'NO_DISCOUNT',
      },
      fareOptions: {
        isInternationalBookable: false,
        isInternational: false,
        isEticketBuyable: true,
        isPossibleWithOvChipkaart: true,
        isTotalPriceUnknown: false,
      },
      type: 'NS',
      shareUrl: {
        uri: 'https://www.ns.nl/rpx?ctx=arnu%7CfromLocation%3D52.445937%2C4.81496%7CtoLocation%3D52.367926%2C4.882755%7CplannedFromTime%3D2022-04-12T00%3A19%3A00%2B02%3A00%7CoriginWalk%3Dtrue%7CdestinationWalk%3Dtrue%7CplannedArrivalTime%3D2022-04-12T01%3A07%3A00%2B02%3A00%7CyearCard%3Dfalse%7CexcludeHighSpeedTrains%3Dfalse%7CsearchForAccessibleTrip%3Dfalse',
      },
      realtime: true,
      routeId: '=KRkakyaBdA==',
      registerJourney: {
        url: 'https://treinwijzer.ns.nl/idp/login?ctxRecon=arnu%7CfromLocation%3D52.445937%2C4.81496%7CtoLocation%3D52.367926%2C4.882755%7CplannedFromTime%3D2022-04-12T00%3A19%3A00%2B02%3A00%7CoriginWalk%3Dtrue%7CdestinationWalk%3Dtrue%7CplannedArrivalTime%3D2022-04-12T01%3A07%3A00%2B02%3A00%7CyearCard%3Dfalse%7CexcludeHighSpeedTrains%3Dfalse%7CsearchForAccessibleTrip%3Dfalse&dateTime=2022-04-11T22%3A58%3A43.964582%2B02%3A00&searchForArrival=false&excludeHighSpeedTrains=false&localTrainsOnly=false&yearCard=false&searchForAccessibleTrip=false&lang=nl&travelAssistance=false',
        searchUrl:
          'https://treinwijzer.ns.nl/idp/login?search=true&dateTime=2022-04-11T22%3A58%3A43.964582%2B02%3A00&searchForArrival=false&excludeHighSpeedTrains=false&localTrainsOnly=false&yearCard=false&searchForAccessibleTrip=false&lang=nl&travelAssistance=false',
        status: 'REGISTRATION_POSSIBLE',
        bicycleReservationRequired: false,
        availability: {
          seats: true,
          numberOfSeats: 598,
          bicycle: true,
          numberOfBicyclePlaces: 9,
        },
      },
    },
  ],
};
